In [1]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import os, sys
sys.path.append(os.getcwd()[:os.getcwd().rfind(os.sep)])

In [3]:
# 유틸함수 사용
from marcap_utils import marcap_date
from marcap_utils import marcap_date_range

In [10]:
df = marcap_date_range('2010-01-01', '2018-11-15', targetFolder = '../data')

print('row count:', len(df))
df.head()

row count: 4494646

,Code,Name,Close,Changes,ChagesRatio,Volume,Amount,Open,High,Low,Marcap,MarcapRatio,Stocks,ForeignShares,ForeignRatio,Rank,Date
0,005930,삼성전자,809000.0,10000.0,1.2,239271.0,1.925670e+11,803000.0,809000.0,800000.0,1.191652e+14,12.12,147299337.0,70256289.0,47.70,1.0,2010-01-04
1,005490,포스코,612000.0,-6000.0,-1,133963.0,8.189218e+10,610000.0,619000.0,608000.0,5.335834e+13,5.43,87186835.0,43694144.0,50.12,2.0,2010-01-04
2,005380,현대자동차,119000.0,-2000.0,-1.6,1606672.0,1.908472e+11,119500.0,120500.0,118000.0,2.621290e+13,2.67,220276479.0,80142843.0,36.38,3.0,2010-01-04
3,105560,KB금융,59400.0,-300.0,-0.5,1201665.0,7.114752e+10,59700.0,60100.0,58500.0,2.294929e+13,2.33,386351693.0,227740369.0,58.95,4.0,2010-01-04
4,015760,한국전력공사,34250.0,150.0,0.4,1924201.0,6.572431e+10,33800.0,34300.0,33800.0,2.197369e+13,2.23,641567712.0,162987177.0,25.40,5.0,2010-01-04